import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { toast } from "sonner";
import { Link2, Copy, Users, DollarSign } from "lucide-react";

export default function AffiliatesPanel() {
  const { data: affiliate } = trpc.social.affiliateInfo.useQuery();

  const copyCode = () => {
    if (affiliate?.referralCode) {
      navigator.clipboard.writeText(`${window.location.origin}/?ref=${affiliate.referralCode}`);
      toast.success("Referral link copied!");
    }
  };

  return (
    <div className="p-6 max-w-3xl mx-auto">
      <div className="mb-8">
        <div className="flex items-center gap-3 mb-1">
          <div className="h-px w-6 bg-foreground/30"></div>
          <span className="text-xs tracking-[0.15em] uppercase text-muted-foreground">Referrals</span>
        </div>
        <h1 className="font-serif text-3xl font-bold">Affiliate Program</h1>
        <p className="text-muted-foreground text-sm mt-1">Earn 20% commission on every trade made by your referrals.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
        <div className="border border-border p-5 bg-card text-center">
          <Users className="h-6 w-6 mx-auto mb-2 text-muted-foreground" />
          <div className="font-serif text-2xl font-bold">{affiliate?.totalReferrals ?? 0}</div>
          <div className="text-xs text-muted-foreground mt-1">Total Referrals</div>
        </div>
        <div className="border border-border p-5 bg-card text-center">
          <DollarSign className="h-6 w-6 mx-auto mb-2 text-muted-foreground" />
          <div className="font-serif text-2xl font-bold">${parseFloat(affiliate?.totalEarnings ?? "0").toFixed(2)}</div>
          <div className="text-xs text-muted-foreground mt-1">Total Earnings</div>
        </div>
        <div className="border border-border p-5 bg-card text-center">
          <DollarSign className="h-6 w-6 mx-auto mb-2 text-bull" />
          <div className="font-serif text-2xl font-bold text-bull">${parseFloat(affiliate?.pendingEarnings ?? "0").toFixed(2)}</div>
          <div className="text-xs text-muted-foreground mt-1">Pending Payout</div>
        </div>
      </div>

      <div className="border border-border bg-card p-5">
        <h2 className="font-semibold text-sm mb-3">Your Referral Link</h2>
        <div className="flex gap-2">
          <Input readOnly value={affiliate?.referralCode ? `${window.location.origin}/?ref=${affiliate.referralCode}` : "Loading..."} className="font-mono text-xs" />
          <Button variant="outline" onClick={copyCode} className="shrink-0 gap-1.5">
            <Copy className="h-3.5 w-3.5" /> Copy
          </Button>
        </div>
        <p className="text-xs text-muted-foreground mt-3">
          Share your link and earn 20% of all trading commissions generated by your referrals, paid monthly.
        </p>
      </div>
    </div>
  );
}
